#############################################################################
# Makefile for building: qtgo.app/Contents/MacOS/qtgo
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  qtgo.pro
# Template: app
# Command: /Users/jayce/Public/Qt5.7.1/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile qtgo.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers -I../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers -I../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/macx-clang -F/Users/jayce/Public/Qt5.7.1/5.7/clang_64/lib
QMAKE         = /Users/jayce/Public/Qt5.7.1/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qtgo1.0.0
DISTDIR = /Users/jayce/Documents/workspace/cpp/qtgo/.tmp/qtgo1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/jayce/Public/Qt5.7.1/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/jayce/Public/Qt5.7.1/5.7/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		ntiss.cpp \
		frame_painter.cpp moc_ntiss.cpp \
		moc_frame_painter.cpp
OBJECTS       = main.o \
		ntiss.o \
		frame_painter.o \
		moc_ntiss.o \
		moc_frame_painter.o
DIST          = graph/lpp_algorithm/out1.txt \
		graph/map_data/graph_config_oldenburgGen.txt \
		graph/map_data/graph_config_sanfrancisco.txt \
		graph/map_data/oldenburgGen_edge.txt \
		graph/map_data/oldenburgGen_node.txt \
		graph/map_data/sanfrancisco_edge.txt \
		graph/map_data/sanfrancisco_node.txt \
		graph/map_data/sanfrancisco_node_bak.txt \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/qdevice.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/unix.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/mac.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/macx.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/clang.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/qconfig.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/toolchain.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/qt.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/resources.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/moc.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/uic.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/lex.prf \
		qtgo.pro ntiss.h \
		graph/lpp_algorithm/ec_sae.h \
		graph/lpp_algorithm/plpca.h \
		graph/lpp_algorithm/replay_attack.h \
		graph/lpp_algorithm/sa.h \
		graph/display.h \
		graph/draw_util.h \
		graph/edge_cluster_edge.h \
		graph/edge_cluster_graph.h \
		graph/edge_cluster_node.h \
		graph/graph.h \
		graph/graph_edge.h \
		graph/graph_node.h \
		graph/lbs_user.h \
		graph/poi.h \
		graph/random_generator.h \
		graph/util.h \
		frame_painter.h main.cpp \
		ntiss.cpp \
		frame_painter.cpp
QMAKE_TARGET  = qtgo
DESTDIR       = 
TARGET        = qtgo.app/Contents/MacOS/qtgo


first: all
####### Build rules

$(TARGET): ui_ntiss.h $(OBJECTS)  
	@test -d qtgo.app/Contents/MacOS/ || mkdir -p qtgo.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtgo.pro ../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/qdevice.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/unix.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/mac.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/macx.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/clang.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/qconfig.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/toolchain.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/qt.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/resources.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/moc.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/uic.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/lex.prf \
		qtgo.pro \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile qtgo.pro
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/qdevice.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/device_config.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/unix.conf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/mac.conf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/macx.conf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/sanitize.conf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/clang.conf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/qconfig.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/qt_config.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/toolchain.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/toolchain.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/default_pre.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/default_post.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/qml_debug.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/warn_on.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/qt.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/resources.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/moc.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/uic.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/file_copies.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/exceptions.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/yacc.prf:
../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/features/lex.prf:
qtgo.pro:
../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile qtgo.pro

qmake_all: FORCE

qtgo.app/Contents/PkgInfo: 
	@test -d qtgo.app/Contents || mkdir -p qtgo.app/Contents
	@$(DEL_FILE) qtgo.app/Contents/PkgInfo
	@echo "APPL????" > qtgo.app/Contents/PkgInfo
qtgo.app/Contents/Resources/empty.lproj: 
	@test -d qtgo.app/Contents/Resources || mkdir -p qtgo.app/Contents/Resources
	@touch qtgo.app/Contents/Resources/empty.lproj
	
qtgo.app/Contents/Info.plist: 
	@test -d qtgo.app/Contents || mkdir -p qtgo.app/Contents
	@$(DEL_FILE) qtgo.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,ntiss.qtgo,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,qtgo,g" -e "s,@LIBRARY@,qtgo,g" -e "s,@TYPEINFO@,????,g" ../../../../Public/Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >qtgo.app/Contents/Info.plist

all: Makefile \
		qtgo.app/Contents/PkgInfo \
		qtgo.app/Contents/Resources/empty.lproj \
		qtgo.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ntiss.h graph/lpp_algorithm/ec_sae.h graph/lpp_algorithm/plpca.h graph/lpp_algorithm/replay_attack.h graph/lpp_algorithm/sa.h graph/display.h graph/draw_util.h graph/edge_cluster_edge.h graph/edge_cluster_graph.h graph/edge_cluster_node.h graph/graph.h graph/graph_edge.h graph/graph_node.h graph/lbs_user.h graph/poi.h graph/random_generator.h graph/util.h frame_painter.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp ntiss.cpp frame_painter.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ntiss.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r qtgo.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_ntiss.cpp moc_frame_painter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ntiss.cpp moc_frame_painter.cpp
moc_ntiss.cpp: ../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		ntiss.h \
		../../../../Public/Qt5.7.1/5.7/clang_64/bin/moc
	/Users/jayce/Public/Qt5.7.1/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/jayce/Public/Qt5.7.1/5.7/clang_64/mkspecs/macx-clang -I/Users/jayce/Documents/workspace/cpp/qtgo -I/Users/jayce/Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/jayce/Public/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/jayce/Public/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/jayce/Public/Qt5.7.1/5.7/clang_64/lib ntiss.h -o moc_ntiss.cpp

moc_frame_painter.cpp: ../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		frame_painter.h \
		../../../../Public/Qt5.7.1/5.7/clang_64/bin/moc
	/Users/jayce/Public/Qt5.7.1/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/jayce/Public/Qt5.7.1/5.7/clang_64/mkspecs/macx-clang -I/Users/jayce/Documents/workspace/cpp/qtgo -I/Users/jayce/Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/jayce/Public/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/jayce/Public/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/jayce/Public/Qt5.7.1/5.7/clang_64/lib frame_painter.h -o moc_frame_painter.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_ntiss.h
compiler_uic_clean:
	-$(DEL_FILE) ui_ntiss.h
ui_ntiss.h: ntiss.ui \
		../../../../Public/Qt5.7.1/5.7/clang_64/bin/uic \
		frame_painter.h \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/qframe.h
	/Users/jayce/Public/Qt5.7.1/5.7/clang_64/bin/uic ntiss.ui -o ui_ntiss.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ntiss.h \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ntiss.o: ntiss.cpp ntiss.h \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		ui_ntiss.h \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ntiss.o ntiss.cpp

frame_painter.o: frame_painter.cpp frame_painter.h \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/Qpainter \
		../../../../Public/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frame_painter.o frame_painter.cpp

moc_ntiss.o: moc_ntiss.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ntiss.o moc_ntiss.cpp

moc_frame_painter.o: moc_frame_painter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frame_painter.o moc_frame_painter.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

